name: music
description: "A new Flutter project."
publish_to: 'none'
version: 1.4.11+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  on_audio_query:
    path: ./on_audio_query
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  audio_service: ^0.18.18
  path: ^1.9.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  audio_info: ^0.0.3
  marquee: ^2.3.0
  share_plus: ^11.1.0
  cross_file: ^0.3.4+2
  connectivity_plus: ^6.1.5
  http: ^1.5.0
  youtube_explode_dart:
    git:
      url: https://github.com/anandnet/youtube_explode_dart.git
      ref: 1d9ec9baa806705b1d859260eeb389ec28c6b024
  file_selector: ^1.0.3
  audiotags: ^1.4.5
  url_launcher: ^6.3.1
  media_scanner: ^2.2.0
  device_info_plus: ^11.5.0
  dio: ^5.9.0
  open_file: ^3.5.10
  smooth_page_indicator: ^1.2.1
  image: ^4.5.4
  android_intent_plus: ^5.3.0
  package_info_plus: ^8.3.1
  ota_update: ^7.0.2
  scroll_to_index: ^3.0.1
  mini_music_visualizer: ^1.1.4
  flutter_local_notifications: ^19.4.1
  squiggly_slider: ^1.0.5
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/icon/icon_foreground.svg
    - assets/icon/Youtube_logo.png
    - assets/icon/Youtube_Music_icon.png