// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:music/utils/audio/synced_lyrics_service.dart';
import 'package:music/utils/db/download_history_model.dart';
import 'package:music/utils/db/playlist_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DownloadHistoryModelAdapter());
    registerAdapter(LyricsDataAdapter());
    registerAdapter(PlaylistModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DownloadHistoryModelAdapter());
    registerAdapter(LyricsDataAdapter());
    registerAdapter(PlaylistModelAdapter());
  }
}
